
module.exports.always = require('./always');
module.exports.and = require('./and');
module.exports.any = require('./any');
module.exports.at = require('./at');
module.exports.applicable = require('./applicable');
module.exports.apply = require('./apply');
module.exports.batch = require('./batch');
module.exports.binary = require('./binary');
module.exports.bind = require('./bind');
module.exports.callable = require('./callable');
module.exports.compose = require('./compose');
module.exports.concat = require('./concat');
module.exports.copy = require('./copy');
module.exports.curry = require('./curry');
module.exports.curry2 = require('./curry2');
module.exports.curry3 = require('./curry3');
module.exports.defaultto = require('./defaultto');
module.exports.difference = require('./difference');
module.exports.evaluate = require('./evaluate');
module.exports.all = require('./all');
module.exports.filter = require('./filter');
module.exports.find = require('./find');
module.exports.findindex = require('./findindex');
module.exports.flatten = require('./flatten');
module.exports.flatmap = require('./flatmap');
module.exports.flip = require('./flip');
module.exports.format = require('./format');
module.exports.freeze = require('./freeze');
module.exports.haskey = require('./haskey');
module.exports.hasownproperty = require('./hasownproperty');
module.exports.head = require('./head');
module.exports.id = require('./id');
module.exports.includes = require('./includes');
module.exports.indexof = require('./indexof');
module.exports.intersection = require('./intersection');
module.exports.isdeepequal = require('./isdeepequal');
module.exports.isequal = require('./isequal');
module.exports.isgreaterthan = require('./isgreaterthan');
module.exports.isgreaterthanorequal = require('./isgreaterthanorequal');
module.exports.islessthan = require('./islessthan');
module.exports.islessthanorequal = require('./islessthanorequal');
module.exports.iterate = require('./iterate');
module.exports.last = require('./last');
module.exports.length = require('./length');
module.exports.lift = require('./lift');
module.exports.map = require('./map');
module.exports.merge = require('./merge');
module.exports.none = require('./none');
module.exports.noop = require('./noop');
module.exports.not = require('./not');
module.exports.once = require('./once');
module.exports.or = require('./or');
module.exports.papply = require('./papply'); // JSDOC
module.exports.papplyasync = require('./papplyasync'); // JSDOC
module.exports.parsejson = require('./parsejson');
module.exports.partial = require('./partial');
module.exports.pcatch = require('./pcatch'); // JSDOC
module.exports.pcompose = require('./pcompose'); // JSDOC
module.exports.pfinally = require('./pfinally'); // JSDOC
module.exports.pipe = require('./pipe');
module.exports.pluck = require('./pluck');
module.exports.pmap = require('./pmap'); // JSDOC
module.exports.ppipe = require('./ppipe'); // JSDOC
module.exports.predicate = require('./predicate');
module.exports.preject = require('./preject'); // JSDOC
module.exports.presolve = require('./presolve'); // JSDOC
module.exports.ptimeout = require('./ptimeout'); // JSDOC
module.exports.queuemicrotask = require('./queuemicrotask'); // JSDOC
module.exports.reduce = require('./reduce');
module.exports.repeat = require('./repeat');
module.exports.reverse = require('./reverse');
module.exports.separate = require('./separate');
module.exports.slice = require('./slice');
module.exports.split = require('./split');
module.exports.stack = require('./stack');
module.exports.symmetricdifference = require('./symmetricdifference');
module.exports.tail = require('./tail');
module.exports.take = require('./take');
module.exports.tap = require('./tap');
module.exports.timeout = require('./timeout'); // JSDOC
module.exports.tojson = require('./tojson');
module.exports.tostring = require('./tostring');
module.exports.transduce = require('./transduce');
module.exports.transform = require('./transform');
module.exports.transmap = require('./transmap');
module.exports.trim = require('./trim');
module.exports.unary = require('./unary');
module.exports.uniq = require('./uniq');
module.exports.union = require('./union');
module.exports.unless = require('./unless');
module.exports.when = require('./when');
module.exports.where = require('./where');
module.exports.witharity = require('./witharity');
module.exports.without = require('./without');
module.exports.wrap = require('./wrap');
module.exports.xor = require('./xor');
module.exports.zip = require('./zip');
module.exports.zipwith = require('./zipwith');